export const maxVideoSize = 500 * 1024 * 1024 // 500MB
export const allowedVideoTypes = ['video/mp4', 'video/webm', 'video/ogg']
export const maxTitleLength = 3
export const maxDescriptionLength = 10
export const MAX_TITLE_LENGTH_VALIDATION_MESSAGE = `Title must be at most ${maxTitleLength} characters long.`
export const MAX_DESCRIPTION_LENGTH_VALIDATION_MESSAGE = `Description must be at most ${maxDescriptionLength} characters long.`
export const MAX_VIDEO_SIZE_VALIDATION_MESSAGE = `Video file must be less than ${maxVideoSize / (1024 * 1024)} MB.`
export const ALLOWED_VIDEO_TYPES_VALIDATION_MESSAGE = `Video file must be one of the following types: ${allowedVideoTypes.join(', ')}.`
export const EMAIL_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Email is required.'
export const PASSWORD_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Password is required.'
export const FIRST_NAME_REQUIRED_FIELD_VALIDATION_MESSAGE = 'First name is required.'
export const LAST_NAME_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Last name is required.'
export const BIRTHDATE_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Birthdate is required.'
export const PHONE_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Phone number is required.'
export const CONFIRM_PASSWORD_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Confirm Password is required.'
export const TITLE_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Title is required.'
export const DESCRIPTION_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Description is required.'
export const VIDEO_REQUIRED_FIELD_VALIDATION_MESSAGE = 'Video file is required.'